# Google Cloud Platform Configuration
service: default

runtime: custom
env: flex

instance_class: F1

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 3
  cool_down_period_sec: 120
  cpu_utilization:
    target_utilization: 0.65

env_variables:
  NODE_ENV: "production"
  # Database Configuration
  DATABASE_URL: "postgresql://optimale:Test@1234@optimalemain.postgres.database.azure.com:5432/optimaleMd"
  # JWT Configuration
  JWT_SECRET: "your-super-secret-jwt-key-here"
  JWT_EXPIRES_IN: "7d"
  # Stripe Configuration
  STRIPE_SECRET_KEY: "k_live_51RywxfIqcNoCEMxMkOIgvMR3U0YKrmgDvom30whU5eKBBAj6PmVGZpMpWuW3NjjxoCY5oO7xpEahX02yeJGyHKxk00F0FPkLsf"
  STRIPE_PUBLISHABLE_KEY: "pk_live_51RywxfIqcNoCEMxM5387KmbnrLQm1V5gkwpahlRCuHFhJIdFOprGvyphcRrGbQRbQy2okX3kJv1wfSNyJFcaNjCL00BCvRjjAW"
  # Email Configuration
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "465"
  SMTP_USER: "support@optimalemd.health"
  SMTP_PASS: "ekpmrxhircyeogxs"
  SMTP_FROM: "support@optimalemd.health"
  # Google Calendar API Configuration
  GOOGLE_CLIENT_ID: "498337781985-p4248hnlt3hv5vbcvbd0i4tg0rgo26bt.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: "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"
  GOOGLE_REDIRECT_URI: "http://localhost:3000/api/google-calendar/oauth/callback"
  GOOGLE_REFRESH_TOKEN: "1//04gFjz7J7TqC3CgYIARAAGAQSNwF-L9IrGmPEqjq4ooUdArv5mj3F9QavKPSce1oPaUpMKC6Pqbimv6v9o-ofeM5iguT1Hxectus"
  GOOGLE_CALENDAR_ID: "primary"
  DOCTOR_EMAIL: "hassantahir3556@gmail.com"
  FRONTEND_URL: "https://optimalmd-mu.vercel.app"

handlers:
  - url: /.*
    script: auto
    secure: always
