/*
  Warnings:

  - You are about to drop the column `workingHours` on the `doctors` table. All the data in the column will be lost.

*/
-- AlterTable
ALTER TABLE "public"."doctors" DROP COLUMN "workingHours";

-- AlterTable
ALTER TABLE "public"."schedules" ADD COLUMN     "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "workingHoursId" TEXT;

-- CreateTable
CREATE TABLE "public"."working_hours" (
    "id" TEXT NOT NULL,
    "doctorId" TEXT NOT NULL,
    "dayOfWeek" INTEGER NOT NULL,
    "startTime" TEXT NOT NULL,
    "endTime" TEXT NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "slotDuration" INTEGER NOT NULL DEFAULT 20,
    "breakDuration" INTEGER NOT NULL DEFAULT 10,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "working_hours_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "working_hours_doctorId_dayOfWeek_key" ON "public"."working_hours"("doctorId", "dayOfWeek");

-- AddForeignKey
ALTER TABLE "public"."working_hours" ADD CONSTRAINT "working_hours_doctorId_fkey" FOREIGN KEY ("doctorId") REFERENCES "public"."doctors"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."schedules" ADD CONSTRAINT "schedules_workingHoursId_fkey" FOREIGN KEY ("workingHoursId") REFERENCES "public"."working_hours"("id") ON DELETE CASCADE ON UPDATE CASCADE;
