name: Build and Deploy Node.js app to Azure Web App - optimalemd

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build --if-present

      - name: Run Prisma generate
        run: npx prisma generate

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            .
            !node_modules/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Install dependencies (for Prisma)
        run: npm install --production

      - name: Run Prisma generate
        run: npx prisma generate

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_129A1D0672A546CAAB3B61D73745770C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AA2855DFF4484260AB39F7440ABB5F06 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_57A70D711A884D1BBFC55640AD876E9E }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'optimaleproduction'
          slot-name: 'Production'
          package: .

      - name: Set post-deployment startup command
        uses: azure/appservice-settings@v1
        with:
          app-name: 'optimaleproduction'
          slot-name: 'Production'
          app-settings-json: |
            [
              {
                "name": "POST_DEPLOYMENT_COMMAND",
                "value": "npx prisma generate"
              }
            ]